risky: true

preset: psr12

enabled:
    - alpha_ordered_imports
    - binary_operator_spaces
    - blank_line_before_return
    - hash_to_slash_comment
    - linebreak_after_opening_tag
    - method_separation
    - native_function_casing
    - no_alias_functions
    - no_blank_lines_after_phpdoc
    - no_empty_comment
    - no_empty_phpdoc
    - no_empty_statement
    - no_extra_block_blank_lines
    - no_extra_consecutive_blank_lines
    - no_multiline_whitespace_around_double_arrow
    - no_multiline_whitespace_before_semicolons
    - no_short_bool_cast
    - no_singleline_whitespace_before_semicolons
    - no_trailing_comma_in_list_call
    - no_trailing_comma_in_singleline_array
    - no_unneeded_control_parentheses
    - no_unused_imports
    - no_useless_else
    - no_useless_return
    - no_whitespace_before_comma_in_array
    - non_printable_character
    - normalize_index_brace
    - object_operator_without_whitespace
    - phpdoc_add_missing_param_annotation
    - phpdoc_annotation_without_dot
    - phpdoc_indent
    - phpdoc_no_access
    - phpdoc_no_package
    - phpdoc_order
    - phpdoc_scalar
    - phpdoc_single_line_var_spacing
    - phpdoc_trim
    - phpdoc_types
    - phpdoc_var_without_name
    - self_accessor
    - short_array_syntax
    - single_quote
    - standardize_not_equals
    - trailing_comma_in_multiline_array
    - whitespace_after_comma_in_array

finder:
  name:
    - "*.php"
  exclude:
    - ".Build"
    - "doc"
    - "Resources"
  not-name:
    - "ext_emconf.php"
